---
title: "R第二章"
output: html_document
---
### 数据集（观测 属性）
#### 创建数据集的关键步骤
##### (1)选择一种数据结构存储数据
##### (2)将数据导入到这个数据结构中


### 第一部分：数据结构（标量、向量、矩阵、数组、数据框、因子、列表）

##### 标量、向量、矩阵、数组：原理相似，结构扩展，其数据结构中的数据必须是同一类型。
##### 数据框：矩阵的更一般形式，可包含多种不同的数据类型，是数据处理常见格式。
##### 因子：名义变量和有序变量在R中称为因子（factor），可通过factor()函数进行整数对应或数值编码，用于计算机识别计算
##### 列表：列表就是一些对象的有序集合，列表允许你整合若干对象到单个对象名下，可以使用函数list()创建列表

##### 创建向量：
```{r}
a <- c(1,2,3)
b <- c("我","是","谁")
c <- c(TRUE,FALSE)
d <- c(1:100)
print(a)
```
##### 向量索引
```{r}
a <- c(1:100)
a[1]
a[-1]#输出除了1号元素外的其他元素
a[c(1:3)]
a[1:3]
```
##### 向量其他操作
```{r}
# 依条件选取
a[a > 14 & a < 40]
#成员判断
1 %in% a 
# 给每个元素m命名
names(a) <- c(11:110) 
a["19"] 
# 添加元素
a["1111"] <- 101
a
# 删除元素
a[-c(1:3)]

```






##### 创建矩阵：
```{r}
data <- c(1:20)
k <- c("l","g","d","s")
l <- c("r","i","k","g","n")
m <- matrix(data,nrow=4,ncol=5,byrow=FALSE,dimnames=list(k,l))
m
```
##### 矩阵索引：
```{r}
m[2,]
m[,2]
m[1:2,1:3]
m[,"r"]
```
##### 创建数组
```{r}
data <- c(1:36)
n <- array(data,c(3,4,3))
n 
```
##### 数组索引：
```{r}
n[2,,]
n[2,2,]
n[2,2,2]
```






##### 创建数据框
```{r}
a <- c(0, 0, 1.1, 0)
b <- c(4.1, 4.1, 2.1, 1.1)
c <- c("cars.1"," cars.2", "cars.3", "cars.4") 
data <- data.frame(a,b,c)
```
##### 数据框索引
```{r}
data[1]
data[1:3]
data[1,3]
data[2,]
data[,2]
data$a
```





##### 创建因子
```{r}
factor1 <- factor(c) # 名义变量
factor2 <- factor(c,ordered=TRUE,levels <- c( "cars.1" ,"cars.2","cars.3", "cars.4"))# 有序变量,指定顺序大小
factor1
factor2
```




##### 创建列表
```{r}
mylist <- list(stu.id=123,stu.name="tom",stu.marks=c(12,23,41))
mylist
```
##### 列表索引
```{r}
mylist[[3]]
mylist[3]
mylist$stu.id
mode(mylist[[3]])
mode(mylist[3])
#### 查看列表元素名称
names(mylist)
#### 更改列表元素名称
names(mylist) <- c("w","e","r")
names(mylist)
#### 创建新变量
mylist$d <- c(1,2,3)
mylist
#### 删除变量
mylist <- mylist[-4]
mylist
#### 拼接列表
yourlist <- mylist
yourlist
add <- c(mylist,yourlist)
add
#### 列表转向量
unlist(add)
```



