---
title: "数据分析"
author: "巩伟明"
date: "2020/3/7"
output: html_document
---


## 随机数
```{r}
?Geometric
#取正态分布值
x=rnorm(n=100,mean = 15,sd=2)
#QQ图
qqnorm(x)
#生成随机数
runif(1)#默认0-1
runif(50)
runif(50,min=1,max=100)#可设置区间大小
#随机数种子
set.seed(666)
runif(50)
runif(50)
set.seed(666)
runif(50)
```


## 描述性统计
```{r}
#y一般统计
myvars <- mtcars[c("mpg", "hp", "wt", "am")]
summary(myvars)

#分组统计-psych包
library(psych)
describeBy(myvars, group = mtcars$am)

#分组统计-MASS包
library(MASS)
aggregate(Cars93[c("Min.Price","Price","Max.Price","MPG.city")],by=list(Origin=Cars93$Origin),mean)
aggregate(Cars93[c("Min.Price","Price","Max.Price","MPG.city")],by=list(Origin=Cars93$Origin),sd)
aggregate(Cars93[c("Min.Price","Price","Max.Price","MPG.city")],by=list(Origin=Cars93$Origin,Manufacturer=Cars93$Manufacturer),mean)

#分组统计-doBy包
install.packages("doBy")
library(doBy)
x<-summaryBy(mpg+hp+wt~am, data=mtcars)
```

##频数统计
```{r}
# 按因子分组
split(mtcars,mtcars$cyl)
split(mtcars,as.factor(mtcars$cyl))
# 一维列联表
table(mtcars$cyl)
prop.table(table(mtcars$cyl))
prop.table(table(mtcars$cyl))*100
# 二维列联表
library(vcd)
head(Arthritis)
mytable <- table(Arthritis$Treatment,Arthritis$Improved)
with(data = Arthritis,{table(Treatment,Improved)})
mytable <- xtabs(~ Treatment+Improved, data=Arthritis)
# 二维联表行列统计
margin.table(mytable,1) #row sums
margin.table(mytable,2) # column sums
prop.table(mytable) # cell proportions
prop.table(mytable, 1) # row proportions
prop.table(mytable, 2) # column proportions
addmargins(mytable) # add row and column sums to table


mytable <- xtabs(~ Treatment+Sex+Improved, data=Arthritis)
mytable
ftable(mytable) 
margin.table(mytable, 1)
margin.table(mytable, 2)
margin.table(mytable, 2)
margin.table(mytable, c(1,3))
ftable(prop.table(mytable, c(1,2)))
ftable(addmargins(prop.table(mytable, c(1, 2)), 3))
```


## 独立性检验
```{r}
library(vcd)
mytable <- table(Arthritis$Treatment,Arthritis$Improved)
?chisq.test
chisq.test(mytable)
?fisher.test
fisher.test(mytable)
?mantelhaen.test
mytable <- table(Arthritis$Treatment,Arthritis$Sex,Arthritis$Improved)
mantelhaen.test(mytable)
```


## 相关性分析
```{r}
?cor#相关系数
cor(state.x77)
cor(state.x77,method = "spearman")
?cov#协方差
cov(state.x77)
# 指定属性相关系数
x <- state.x77[,c(1,2,3,6)]
y <- state.x77[,c(4,5)]
cor(x,y)
# 偏相关系数
install.packages("ggm")
library(ggm)
colnames(state.x77)
pcor(c(1,5,2,3,6), cov(state.x77))
pcor.test
# 相关系数检验
?cor.test
cor.test(state.x77[,3],state.x77[,5])
library(psych)
corr.test(state.x77)
# 偏相关系数检验
library(ggm)
x <- pcor(c(1,5,2,3,6),cov(state.x77))
pcor.test(x,3,50)
```


## 假设检验检验
```{r}
# t test
library(MASS)
t.test(Prob ~ So, data=UScrime)


# dependent t test
sapply(UScrime[c("U1","U2")], function(x)(c(mean=mean(x),sd=sd(x))))
with(UScrime, t.test(U1, U2, paired=TRUE))


# Wilcoxon two group comparison
with(UScrime, by(Prob, So, median))
wilcox.test(Prob ~ So, data=UScrime)

sapply(UScrime[c("U1", "U2")], median)
with(UScrime, wilcox.test(U1, U2, paired=TRUE))


# Kruskal Wallis test
states <- data.frame(state.region, state.x77)
kruskal.test(Illiteracy ~ state.region, data=states)


#Nonparametric multiple comparisons
source("http://www.statmethods.net/RiA/wmc.txt")              
states <- data.frame(state.region, state.x77)
wmc(Illiteracy ~ state.region, data=states, method="holm")
```

